version: '3'

# Global variables - paths and ports used throughout tasks
vars:
  # Directories
  DIR_LOGS: logs
  DIR_TMP: tmp
  DIR_TESTS: tests
  DIR_NODE_MODULES: tests/node_modules

  # Test outputs (organized)
  DIR_TEST_OUTPUTS: tests/outputs
  DIR_TEST_REPORTS: tests/outputs/reports
  DIR_TEST_ARTIFACTS: tests/outputs/artifacts
  DIR_PLAYWRIGHT_CACHE: /Users/apple/Library/Caches/ms-playwright

  # Ports
  PORT_HTTPS: "3443"
  PORT_BACKEND: "3000"

  # Files - Certificates
  FILE_CERT: localhost.pem
  FILE_KEY: localhost-key.pem

  # Files - Configuration
  FILE_CADDY_PID: .caddy.pid
  FILE_AIR_CONFIG: .air.toml
  FILE_CADDYFILE: Caddyfile

  # Files - Logs
  FILE_SERVER_LOG: "{{.DIR_LOGS}}/server.log"
  FILE_CADDY_LOG: "{{.DIR_LOGS}}/caddy.log"
  FILE_BUILD_LOG: "{{.DIR_LOGS}}/build-errors.log"
  FILE_PLAYWRIGHT_TEST_LOG: "{{.DIR_LOGS}}/playwright-test.log"
  FILE_PLAYWRIGHT_HEADED_LOG: "{{.DIR_LOGS}}/playwright-test-headed.log"
  FILE_PLAYWRIGHT_UI_LOG: "{{.DIR_LOGS}}/playwright-test-ui.log"
  FILE_PLAYWRIGHT_DEBUG_LOG: "{{.DIR_LOGS}}/playwright-test-debug.log"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  _internal_vars:
    desc: Display all configured variables (useful for debugging)
    cmds:
      - |
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo "  ðŸ“‹ Taskfile Variables"
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo "Directories:"
        echo "  DIR_LOGS:                  {{.DIR_LOGS}}"
        echo "  DIR_TMP:                   {{.DIR_TMP}}"
        echo "  DIR_NODE_MODULES:          {{.DIR_NODE_MODULES}}"
        echo "  DIR_TEST_RESULTS:          {{.DIR_TEST_RESULTS}}"
        echo "  DIR_PLAYWRIGHT_REPORT:     {{.DIR_PLAYWRIGHT_REPORT}}"
        echo "  DIR_PLAYWRIGHT_CACHE:      {{.DIR_PLAYWRIGHT_CACHE}}"
        echo ""
        echo "Ports:"
        echo "  PORT_HTTPS:                {{.PORT_HTTPS}}"
        echo "  PORT_BACKEND:              {{.PORT_BACKEND}}"
        echo ""
        echo "Files - Certificates:"
        echo "  FILE_CERT:                 {{.FILE_CERT}}"
        echo "  FILE_KEY:                  {{.FILE_KEY}}"
        echo ""
        echo "Files - Configuration:"
        echo "  FILE_CADDY_PID:            {{.FILE_CADDY_PID}}"
        echo "  FILE_AIR_CONFIG:           {{.FILE_AIR_CONFIG}}"
        echo "  FILE_CADDYFILE:            {{.FILE_CADDYFILE}}"
        echo ""
        echo "Files - Logs:"
        echo "  FILE_SERVER_LOG:           {{.FILE_SERVER_LOG}}"
        echo "  FILE_CADDY_LOG:            {{.FILE_CADDY_LOG}}"
        echo "  FILE_BUILD_LOG:            {{.FILE_BUILD_LOG}}"
        echo "  FILE_PLAYWRIGHT_TEST_LOG:  {{.FILE_PLAYWRIGHT_TEST_LOG}}"
        echo "  FILE_PLAYWRIGHT_HEADED_LOG:{{.FILE_PLAYWRIGHT_HEADED_LOG}}"
        echo "  FILE_PLAYWRIGHT_UI_LOG:    {{.FILE_PLAYWRIGHT_UI_LOG}}"
        echo "  FILE_PLAYWRIGHT_DEBUG_LOG: {{.FILE_PLAYWRIGHT_DEBUG_LOG}}"
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"

  # Development Server (No GUI, but not CI-safe)
  dev:
    desc: "Start HTTPS development server (alias for dev-serve)"
    deps: [dev-serve]

  dev-serve:
    desc: "Start HTTPS development server with live reload (Cookie mode - default)"
    deps: [_internal_gen_gitignore, _internal_install_air, _internal_install_caddy, _internal_install_mkcert, _internal_setup_logs]
    cmds:
      - task: _internal_setup_air
        vars: {SESSION_MODE: "cookie"}
      - task: _internal_generate_certs
      - task: _internal_start_caddy
      - task: _internal_print_urls
      - air 2>&1 | tee {{.FILE_SERVER_LOG}}

  dev-serve-url:
    desc: "Start HTTPS development server with URL parameter mode (cross-browser sync)"
    deps: [_internal_gen_gitignore, _internal_install_air, _internal_install_caddy, _internal_install_mkcert, _internal_setup_logs]
    cmds:
      - task: _internal_setup_air
        vars: {SESSION_MODE: "url"}
      - task: _internal_generate_certs
      - task: _internal_start_caddy
      - task: _internal_print_urls
      - air 2>&1 | tee {{.FILE_SERVER_LOG}}

  dev-serve-both:
    desc: "Start HTTPS development server with hybrid mode (URL + Cookie fallback)"
    deps: [_internal_gen_gitignore, _internal_install_air, _internal_install_caddy, _internal_install_mkcert, _internal_setup_logs]
    cmds:
      - task: _internal_setup_air
        vars: {SESSION_MODE: "both"}
      - task: _internal_generate_certs
      - task: _internal_start_caddy
      - task: _internal_print_urls
      - air 2>&1 | tee {{.FILE_SERVER_LOG}}

  dev-kill:
    desc: "Stop all running dev servers"
    cmds:
      - killall -9 air 2>/dev/null || echo "No Air processes running"
      - killall -9 caddy 2>/dev/null || echo "No Caddy processes running"
      - killall -9 main 2>/dev/null || echo "No main processes running"

  _internal_clean:
    desc: Clean logs, test outputs, and build artifacts (keeps Playwright browser cache)
    cmds:
      - rm -rf {{.DIR_LOGS}}/
      - rm -rf {{.DIR_TEST_OUTPUTS}}/
      - rm -rf {{.DIR_TMP}}/
      - echo "âœ… Cleaned logs, test outputs, and build artifacts"

  _internal_clean_playwright_cache:
    desc: Clean Playwright browser cache (WARNING - will re-download ~500MB of browsers!)
    cmds:
      - rm -rf {{.DIR_PLAYWRIGHT_CACHE}} || echo "Playwright cache already clean"
      - echo "âš ï¸  Playwright browser cache deleted - run 'task install_playwright' to reinstall"

  _internal_install_playwright:
    desc: Manually install/reinstall Playwright browsers (~500MB download)
    deps: [_internal_install_bun]
    cmds:
      - cd {{.DIR_TESTS}} && bun playwright install
      - echo "âœ… Playwright browsers installed to {{.DIR_PLAYWRIGHT_CACHE}}"

  # Manual Testing (Opens GUI - 2 browser windows for manual testing)
  dev-open-safari:
    desc: "[GUI] Open 2 Safari windows side-by-side for manual testing"
    cmds:
      - |
        LAN_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n1)
        {{.DIR_TESTS}}/manual/test-browser.sh safari https://${LAN_IP}:{{.PORT_HTTPS}}

  dev-open-chrome:
    desc: "[GUI] Open 2 Chrome windows side-by-side for manual testing"
    cmds:
      - |
        LAN_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n1)
        {{.DIR_TESTS}}/manual/test-browser.sh chrome https://${LAN_IP}:{{.PORT_HTTPS}}

  dev-open-firefox:
    desc: "[GUI] Open 2 Firefox windows side-by-side for manual testing"
    cmds:
      - |
        LAN_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n1)
        {{.DIR_TESTS}}/manual/test-browser.sh firefox https://${LAN_IP}:{{.PORT_HTTPS}}

  # CI/CD Tasks (Headless, No GUI)
  test:
    desc: "[CI] Run all tests headless (CI/CD safe)"
    deps: [_internal_gen_playwright, _internal_install_bun, _internal_install_playwright_deps, _internal_setup_logs]
    cmds:
      - cd {{.DIR_TESTS}} && bun playwright test 2>&1 | tee ../{{.FILE_PLAYWRIGHT_TEST_LOG}}

  # Automated Testing with GUI (Opens Playwright UI or browser windows)
  test-ui:
    desc: "[GUI] Playwright interactive UI (RECOMMENDED - single window, full control)"
    deps: [_internal_gen_playwright, _internal_install_bun, _internal_install_playwright_deps, _internal_setup_logs]
    cmds:
      - cd {{.DIR_TESTS}} && bun playwright test --ui 2>&1 | tee ../{{.FILE_PLAYWRIGHT_UI_LOG}}

  test-debug:
    desc: "[GUI] Playwright step-through debugging mode"
    deps: [_internal_gen_playwright, _internal_install_bun, _internal_install_playwright_deps, _internal_setup_logs]
    cmds:
      - cd {{.DIR_TESTS}} && bun playwright test --debug 2>&1 | tee ../{{.FILE_PLAYWRIGHT_DEBUG_LOG}}

  test-chromium:
    desc: "[GUI] Run tests in Chromium only (headed mode)"
    deps: [_internal_gen_playwright, _internal_install_bun, _internal_install_playwright_deps, _internal_setup_logs]
    cmds:
      - cd {{.DIR_TESTS}} && bun playwright test --headed --project=chromium 2>&1 | tee ../{{.FILE_PLAYWRIGHT_HEADED_LOG}}

  test-webkit:
    desc: "[GUI] Run tests in WebKit/Safari only (headed mode)"
    deps: [_internal_gen_playwright, _internal_install_bun, _internal_install_playwright_deps, _internal_setup_logs]
    cmds:
      - cd {{.DIR_TESTS}} && bun playwright test --headed --project=webkit 2>&1 | tee ../{{.FILE_PLAYWRIGHT_HEADED_LOG}}

  test-report:
    desc: "[GUI] Open HTML test report in browser"
    cmds:
      - cd {{.DIR_TESTS}} && bun playwright show-report

  # Internal tasks
  _internal_gen_playwright:
    desc: Generate Playwright test specs from test-matrix.yml
    deps: [_install-bun]
    sources:
      - "{{.DIR_TESTS}}/test-matrix.yml"
      - "{{.DIR_TESTS}}/scripts/gen-playwright-tests.ts"
    generates:
      - "{{.DIR_TESTS}}/specs/*.spec.ts"
    cmds:
      - cd {{.DIR_TESTS}} && bun run scripts/gen-playwright-tests.ts

  _internal_setup_logs:
    desc: Create logs directory if it doesn't exist
    cmds:
      - mkdir -p {{.DIR_LOGS}}
    status:
      - test -d {{.DIR_LOGS}}

  _internal_install_air:
    desc: Install Air live reload tool
    cmds:
      - go install github.com/air-verse/air@latest
    status:
      - test -f $(go env GOPATH)/bin/air

  _internal_install_caddy:
    desc: Install Caddy web server
    cmds:
      - go install github.com/caddyserver/caddy/v2/cmd/caddy@latest
    status:
      - test -f $(go env GOPATH)/bin/caddy

  _internal_install_mkcert:
    desc: Install mkcert for local HTTPS certificates
    cmds:
      - |
        if [ ! -f $(go env GOPATH)/bin/mkcert ]; then
          go install filippo.io/mkcert@latest
        fi
      - |
        if ! mkcert -CAROOT &>/dev/null || [ ! -d "$(mkcert -CAROOT)" ]; then
          mkcert -install
        fi
    status:
      - test -f $(go env GOPATH)/bin/mkcert
      - test -d "$(mkcert -CAROOT 2>/dev/null)"

  _internal_generate_certs:
    desc: Generate SSL certificates for localhost and LAN IP
    cmds:
      - |
        LAN_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n1)
        if [ ! -f {{.FILE_CERT}} ] || [ ! -f {{.FILE_KEY}} ]; then
          echo "Generating mkcert certificates for localhost and ${LAN_IP}..."
          mkcert -cert-file {{.FILE_CERT}} -key-file {{.FILE_KEY}} localhost 127.0.0.1 ::1 ${LAN_IP}
        fi
    sources:
      - Taskfile.yml
    generates:
      - "{{.FILE_CERT}}"
      - "{{.FILE_KEY}}"

  _internal_generate_caddyfile:
    desc: Generate Caddyfile from template with Taskfile variables
    sources:
      - Caddyfile.template
      - Taskfile.yml
    generates:
      - "{{.FILE_CADDYFILE}}"
    cmds:
      - |
        # Generate Caddyfile from Caddyfile.template
        sed -e 's|{{"{{"}}\.PORT_HTTPS{{"}}"}}|{{.PORT_HTTPS}}|g' \
            -e 's|{{"{{"}}\.FILE_CERT{{"}}"}}|{{.FILE_CERT}}|g' \
            -e 's|{{"{{"}}\.FILE_KEY{{"}}"}}|{{.FILE_KEY}}|g' \
            -e 's|{{"{{"}}\.PORT_BACKEND{{"}}"}}|{{.PORT_BACKEND}}|g' \
            Caddyfile.template > {{.FILE_CADDYFILE}}

  _internal_start_caddy:
    desc: Start Caddy reverse proxy in background
    deps: [_internal_setup_logs, _internal_generate_caddyfile]
    cmds:
      - |
        # Stop any existing Caddy
        killall -9 caddy 2>/dev/null || true
        sleep 1
        # Start Caddy in background (log to {{.FILE_CADDY_LOG}})
        nohup caddy run --config {{.FILE_CADDYFILE}} > {{.FILE_CADDY_LOG}} 2>&1 &
        echo $! > {{.FILE_CADDY_PID}}
        sleep 2

  _internal_setup_air:
    desc: Configure Air live reload with session mode
    deps: [_internal_setup_logs]
    vars:
      SESSION_MODE: '{{.SESSION_MODE | default "cookie"}}'
    cmds:
      - |
        # Always recreate Air config with session mode flag
        cat > {{.FILE_AIR_CONFIG}} << 'EOF'
        root = "."
        tmp_dir = "{{.DIR_TMP}}"

        [build]
          bin = "./{{.DIR_TMP}}/main"
          cmd = "env GOWORK=off go build -o ./{{.DIR_TMP}}/main ."
          args_bin = ["-session-mode", "{{.SESSION_MODE}}"]
          delay = 1000
          exclude_dir = ["{{.DIR_TMP}}", "vendor", "{{.DIR_LOGS}}"]
          exclude_regex = ["_test.go"]
          include_ext = ["go", "html"]
          kill_delay = "500ms"
          log = "{{.FILE_BUILD_LOG}}"
          send_interrupt = true

        [log]
          main_only = false

        [misc]
          clean_on_exit = false

        [color]
          build = "yellow"
          main = "magenta"
          runner = "green"

        [screen]
          clear_on_rebuild = false
        EOF
        echo "âœ… Air configured for session mode: {{.SESSION_MODE}}"

  _internal_install_bun:
    desc: Install Bun JavaScript runtime
    cmds:
      - |
        if ! command -v bun &> /dev/null; then
          echo "ðŸ“¦ Installing Bun..."
          curl -fsSL https://bun.sh/install | bash
          echo "âœ… Bun installed. Restart shell or run: source ~/.bashrc"
        fi
    status:
      - command -v bun

  _internal_install_playwright_deps:
    desc: Install Playwright and its browser dependencies
    deps: [_internal_install_bun]
    cmds:
      - |
        if [ ! -d "{{.DIR_NODE_MODULES}}/playwright" ]; then
          echo "ðŸŽ­ Installing Playwright via Bun..."
          cd {{.DIR_TESTS}} && bun add -d playwright @playwright/test
        fi
      - |
        if [ ! -d "{{.DIR_PLAYWRIGHT_CACHE}}" ]; then
          echo "ðŸ“¦ Installing Playwright browsers (headless)..."
          cd {{.DIR_TESTS}} && bun playwright install --with-deps
        fi
    status:
      - test -d {{.DIR_NODE_MODULES}}/playwright
      - test -d {{.DIR_PLAYWRIGHT_CACHE}}

  _internal_print_urls:
    desc: Print development server URLs
    silent: true
    cmds:
      - |
        LAN_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n1)
        echo ""
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo "  ðŸ”’ HTTPS Development Server (mkcert)"
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo "  Local:   https://localhost:{{.PORT_HTTPS}}"
        if [ -n "$LAN_IP" ]; then
          echo "  Network: https://${LAN_IP}:{{.PORT_HTTPS}}  ðŸ“±"
        fi
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo "  âœ¨ Live reload enabled"
        echo "  ðŸ” Trusted certificates (no warnings!)"
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo ""

  _internal_gen_gitignore:
    desc: Generate .gitignore from Taskfile variables (keeps in sync with build artifacts)
    cmds:
      - |
        cat > .gitignore << 'EOF'
        # Auto-generated from Taskfile.yml - DO NOT EDIT MANUALLY
        # Run 'task gen_gitignore' to regenerate

        # Air live reload
        {{.FILE_AIR_CONFIG}}
        {{.DIR_TMP}}/
        build-errors.log

        # Logs folder (centralized logging)
        {{.DIR_LOGS}}/

        # Task runner
        .task/

        # Caddy (auto-generated config) and certificates
        {{.FILE_CADDYFILE}}
        {{.FILE_CADDY_PID}}
        {{.FILE_CERT}}
        {{.FILE_KEY}}

        # macOS
        .DS_Store

        # Testing
        {{.DIR_NODE_MODULES}}/
        {{.DIR_TESTS}}/bun.lockb
        {{.DIR_TEST_OUTPUTS}}/
        {{.DIR_TESTS}}/.playwright/
        EOF
        echo "âœ… Generated .gitignore from Taskfile variables"
        echo "ðŸ“„ Review: cat .gitignore"
